services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d logsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  log-service:
    build: ./log-service
    container_name: log-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      - GROQ_API_URL=${GROQ_API_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8080:8080"

  vector:
    build: ./vector
    container_name: vector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - log-service

  grafana:
    build: ./grafana
    container_name: grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true

volumes:
  postgres_data: