services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d logsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  service1:
    build: ./service1
    container_name: service1-injestor
    depends_on:
      - rabbitmq
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
    ports:
      - "8081:8080"

  service2:
    build: ./service2
    container_name: service2-analyzer
    depends_on:
      - rabbitmq
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
    ports:
      - "8082:8080"

  service3:
    build: ./service3
    container_name: service3-storage
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8083:8080"

volumes:
  postgres_data: